# -*- coding: utf-8 -*-
"""codealpha_language_translation_tool_project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGT9h68E6gpgKl9G0bEcbgsZPv-7QYkM
"""

!pip install -q streamlit
!pip install deep_translator
!pip install translator gTTS

"""prepare a translation engine /deeptranslation library"""

from deep_translator import GoogleTranslator

# Supported Languages Mapping
LANGUAGES = {
    "English": "en",
    "Urdu": "ur",
    "Spanish": "es",
    "French": "fr",
    "German": "de",
    "Arabic": "ar",
    "Hindi": "hi",
    "Italian": "it",
    "Chinese (Simplified)": "zh-CN"
}

def translate_text(text: str, source_lang: str, target_lang: str) -> str:
    """
    Translates input text using deep-translator.
    """
    if not text.strip():
        raise ValueError("Text input cannot be empty.")

    src_code = LANGUAGES.get(source_lang, "auto")
    tgt_code = LANGUAGES.get(target_lang, "en")

    translator = GoogleTranslator(source=src_code, target=tgt_code)
    return translator.translate(text)

"""now text-speech converter / streamlit"""

from gtts import gTTS
import io

def generate_audio_bytes(text: str, target_lang: str) -> io.BytesIO:
    """
    Converts translated text into MP3 audio in-memory.
    """
    tgt_code = LANGUAGES.get(target_lang, "en").lower()

    # Generate speech
    tts = gTTS(text=text, lang=tgt_code)

    # Store in memory buffer without saving to disk
    audio_fp = io.BytesIO()
    tts.write_to_fp(audio_fp)
    audio_fp.seek(0)

    return audio_fp

"""user interface"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from deep_translator import GoogleTranslator
# from gtts import gTTS
# import io
# 
# # 1. Configuration & Styling
# st.set_page_config(page_title="AI Translation & Audio Hub", page_icon="🌐", layout="centered")
# 
# st.title("🌐 AI Text & Speech Translator")
# st.write("Translate text instantly, copy output, and listen to spoken audio.")
# 
# # 2. Supported Languages Mapping
# LANGUAGES = {
#     "English": "en",
#     "Urdu": "ur",
#     "Spanish": "es",
#     "French": "fr",
#     "German": "de",
#     "Arabic": "ar",
#     "Hindi": "hi",
#     "Italian": "it",
#     "Chinese (Simplified)": "zh-CN"
# }
# 
# # 3. User Controls
# col1, col2 = st.columns(2)
# with col1:
#     source_lang = st.selectbox("Source Language:", list(LANGUAGES.keys()))
# with col2:
#     target_lang = st.selectbox("Target Language:", list(LANGUAGES.keys()), index=1)
# 
# text_input = st.text_area("Enter Text:", height=150, placeholder="Type or paste text here...")
# 
# # 4. App Logic
# if st.button("Translate", type="primary"):
#     if not text_input.strip():
#         st.warning("Please enter text to translate.")
#     else:
#         try:
#             # Translation Execution
#             src_code = LANGUAGES[source_lang]
#             tgt_code = LANGUAGES[target_lang]
#             translated_result = GoogleTranslator(source=src_code, target=tgt_code).translate(text_input)
# 
#             st.markdown("### **Translated Output:**")
#             st.code(translated_result, language=None)  # Includes built-in copy button
# 
#             # Audio Generation Execution
#             tts_lang = tgt_code.lower()
#             tts = gTTS(text=translated_result, lang=tts_lang)
#             audio_fp = io.BytesIO()
#             tts.write_to_fp(audio_fp)
#             audio_fp.seek(0)
# 
#             st.markdown("🔊 **Listen to Speech:**")
#             st.audio(audio_fp, format="audio/mp3")
# 
#         except Exception as e:
#             st.error(f"Execution Error: {e}")

# Download cloudflared if not already present
!wget -q -c https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

# Launch Streamlit and Tunnel
import subprocess
subprocess.Popen(["streamlit", "run", "app.py"])
!./cloudflared tunnel --url http://localhost:8501